///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace launchMyrian
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the launchMyrianRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("74cf8cce-d01d-43ff-8862-094875b5d0f6")]
    public partial class launchMyrianRepository : RepoGenBaseFolder
    {
        static launchMyrianRepository instance = new launchMyrianRepository();
        launchMyrianRepositoryFolders.MyrianAppFolder _myrian;
        launchMyrianRepositoryFolders.SectraMyrianAppFolder _sectramyrian;
        launchMyrianRepositoryFolders.ServeurDactivationIntrouvableAppFolder _serveurdactivationintrouvable;

        /// <summary>
        /// Gets the singleton class instance representing the launchMyrianRepository element repository.
        /// </summary>
        [RepositoryFolder("74cf8cce-d01d-43ff-8862-094875b5d0f6")]
        public static launchMyrianRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public launchMyrianRepository() 
            : base("launchMyrianRepository", "/", null, 0, false, "74cf8cce-d01d-43ff-8862-094875b5d0f6", ".\\RepositoryImages\\launchMyrianRepository74cf8cce.rximgres")
        {
            _myrian = new launchMyrianRepositoryFolders.MyrianAppFolder(this);
            _sectramyrian = new launchMyrianRepositoryFolders.SectraMyrianAppFolder(this);
            _serveurdactivationintrouvable = new launchMyrianRepositoryFolders.ServeurDactivationIntrouvableAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("74cf8cce-d01d-43ff-8862-094875b5d0f6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Myrian folder.
        /// </summary>
        [RepositoryFolder("4084737d-23fb-46d1-b4e0-4c0797529703")]
        public virtual launchMyrianRepositoryFolders.MyrianAppFolder Myrian
        {
            get { return _myrian; }
        }

        /// <summary>
        /// The SectraMyrian folder.
        /// </summary>
        [RepositoryFolder("03be1b1d-6e8b-4181-9336-f0579cfe4bfd")]
        public virtual launchMyrianRepositoryFolders.SectraMyrianAppFolder SectraMyrian
        {
            get { return _sectramyrian; }
        }

        /// <summary>
        /// The ServeurDactivationIntrouvable folder.
        /// </summary>
        [RepositoryFolder("b5798d18-0cd3-4264-95d3-cb4c85f444c2")]
        public virtual launchMyrianRepositoryFolders.ServeurDactivationIntrouvableAppFolder ServeurDactivationIntrouvable
        {
            get { return _serveurdactivationintrouvable; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class launchMyrianRepositoryFolders
    {
        /// <summary>
        /// The MyrianAppFolder folder.
        /// </summary>
        [RepositoryFolder("4084737d-23fb-46d1-b4e0-4c0797529703")]
        public partial class MyrianAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text573Info;
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _adminInfo;
            RepoItemInfo _intrasenseInfo;
            RepoItemInfo _admin1Info;
            RepoItemInfo _combobox880Info;
            RepoItemInfo _text574Info;
            RepoItemInfo _text881Info;
            RepoItemInfo _text575Info;
            RepoItemInfo _text882Info;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _quitterInfo;
            RepoItemInfo _text850Info;
            RepoItemInfo _systemeInfo;
            RepoItemInfo _systeme1Info;
            RepoItemInfo _fermerInfo;
            RepoItemInfo _sectramyrianouverturedesessionInfo;

            /// <summary>
            /// Creates a new Myrian  folder.
            /// </summary>
            public MyrianAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Myrian", "/form[@title~'^Sectra\\ Myrian\\ \\ -\\ Ouvertur']", parentFolder, 30000, null, false, "4084737d-23fb-46d1-b4e0-4c0797529703", "")
            {
                _text573Info = new RepoItemInfo(this, "Text573", "text[@controlid='573']", 30000, null, "149f2560-b003-4641-8239-b4ee34cbab36");
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "?/?/button[@text='>']", 30000, null, "c9325035-72eb-4255-92e7-09fa67907fc5");
                _adminInfo = new RepoItemInfo(this, "Admin", "combobox[@controlid='880']/?/?/listitem[@text='admin']", 30000, null, "8332c446-2d79-4fe6-aafd-272a2a8fc6be");
                _intrasenseInfo = new RepoItemInfo(this, "Intrasense", "combobox[@controlid='880']/?/?/listitem[@text='Intrasense']", 30000, null, "f7bd672d-a48f-4986-85eb-5c2fe32583c4");
                _admin1Info = new RepoItemInfo(this, "Admin1", "?/?/list", 30000, null, "9cb3027d-f023-40c9-886b-947d7ef9f3cc");
                _combobox880Info = new RepoItemInfo(this, "ComboBox880", "combobox[@controlid='880']", 30000, null, "a2d86795-3e24-4b82-8da0-44251cc47753");
                _text574Info = new RepoItemInfo(this, "Text574", "text[@controlid='574']", 30000, null, "6b6d2f82-604e-4f85-9390-8c303ae0e1a1");
                _text881Info = new RepoItemInfo(this, "Text881", "text[@controlid='881']", 30000, null, "2262451a-4a94-472d-9e87-69c26b19a2df");
                _text575Info = new RepoItemInfo(this, "Text575", "text[@controlid='575']", 30000, null, "117cc03f-c36f-450b-83c8-8af581d34d1a");
                _text882Info = new RepoItemInfo(this, "Text882", "text[@controlid='882']", 30000, null, "7d720947-c00d-44df-9bac-622cb3959bf8");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "02bb4fe4-2ad3-4fce-9f2a-b6e1191b87e8");
                _quitterInfo = new RepoItemInfo(this, "Quitter", "button[@text='Quitter']", 30000, null, "6b86c337-78b5-4b48-aa87-b9d39966a5df");
                _text850Info = new RepoItemInfo(this, "Text850", "text[@controlid='850']", 30000, null, "053bf968-422d-4e5d-8004-2aa4c345c67f");
                _systemeInfo = new RepoItemInfo(this, "Systeme", "?/?/menuitem[@accessiblename='Système']", 30000, null, "686c89c9-a7ed-4896-bcc8-c91f8414fceb");
                _systeme1Info = new RepoItemInfo(this, "Systeme1", "menubar[@accessiblename='Système']", 30000, null, "aa9b1792-9fde-4960-aa9f-de756481fc2d");
                _fermerInfo = new RepoItemInfo(this, "Fermer", "?/?/button[@accessiblename='Fermer']", 30000, null, "04b022fe-ae5a-470f-b52b-f5c14ba98aec");
                _sectramyrianouverturedesessionInfo = new RepoItemInfo(this, "SectraMyrianOuvertureDeSession", "titlebar[@accessiblerole='TitleBar']", 30000, null, "4868a807-5af9-437c-b064-686b6ab1bbdc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4084737d-23fb-46d1-b4e0-4c0797529703")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4084737d-23fb-46d1-b4e0-4c0797529703")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text573 item.
            /// </summary>
            [RepositoryItem("149f2560-b003-4641-8239-b4ee34cbab36")]
            public virtual Ranorex.Text Text573
            {
                get
                {
                    return _text573Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text573 item info.
            /// </summary>
            [RepositoryItemInfo("149f2560-b003-4641-8239-b4ee34cbab36")]
            public virtual RepoItemInfo Text573Info
            {
                get
                {
                    return _text573Info;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("c9325035-72eb-4255-92e7-09fa67907fc5")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("c9325035-72eb-4255-92e7-09fa67907fc5")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The Admin item.
            /// </summary>
            [RepositoryItem("8332c446-2d79-4fe6-aafd-272a2a8fc6be")]
            public virtual Ranorex.ListItem Admin
            {
                get
                {
                    return _adminInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Admin item info.
            /// </summary>
            [RepositoryItemInfo("8332c446-2d79-4fe6-aafd-272a2a8fc6be")]
            public virtual RepoItemInfo AdminInfo
            {
                get
                {
                    return _adminInfo;
                }
            }

            /// <summary>
            /// The Intrasense item.
            /// </summary>
            [RepositoryItem("f7bd672d-a48f-4986-85eb-5c2fe32583c4")]
            public virtual Ranorex.ListItem Intrasense
            {
                get
                {
                    return _intrasenseInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Intrasense item info.
            /// </summary>
            [RepositoryItemInfo("f7bd672d-a48f-4986-85eb-5c2fe32583c4")]
            public virtual RepoItemInfo IntrasenseInfo
            {
                get
                {
                    return _intrasenseInfo;
                }
            }

            /// <summary>
            /// The Admin1 item.
            /// </summary>
            [RepositoryItem("9cb3027d-f023-40c9-886b-947d7ef9f3cc")]
            public virtual Ranorex.List Admin1
            {
                get
                {
                    return _admin1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Admin1 item info.
            /// </summary>
            [RepositoryItemInfo("9cb3027d-f023-40c9-886b-947d7ef9f3cc")]
            public virtual RepoItemInfo Admin1Info
            {
                get
                {
                    return _admin1Info;
                }
            }

            /// <summary>
            /// The ComboBox880 item.
            /// </summary>
            [RepositoryItem("a2d86795-3e24-4b82-8da0-44251cc47753")]
            public virtual Ranorex.ComboBox ComboBox880
            {
                get
                {
                    return _combobox880Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox880 item info.
            /// </summary>
            [RepositoryItemInfo("a2d86795-3e24-4b82-8da0-44251cc47753")]
            public virtual RepoItemInfo ComboBox880Info
            {
                get
                {
                    return _combobox880Info;
                }
            }

            /// <summary>
            /// The Text574 item.
            /// </summary>
            [RepositoryItem("6b6d2f82-604e-4f85-9390-8c303ae0e1a1")]
            public virtual Ranorex.Text Text574
            {
                get
                {
                    return _text574Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text574 item info.
            /// </summary>
            [RepositoryItemInfo("6b6d2f82-604e-4f85-9390-8c303ae0e1a1")]
            public virtual RepoItemInfo Text574Info
            {
                get
                {
                    return _text574Info;
                }
            }

            /// <summary>
            /// The Text881 item.
            /// </summary>
            [RepositoryItem("2262451a-4a94-472d-9e87-69c26b19a2df")]
            public virtual Ranorex.Text Text881
            {
                get
                {
                    return _text881Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text881 item info.
            /// </summary>
            [RepositoryItemInfo("2262451a-4a94-472d-9e87-69c26b19a2df")]
            public virtual RepoItemInfo Text881Info
            {
                get
                {
                    return _text881Info;
                }
            }

            /// <summary>
            /// The Text575 item.
            /// </summary>
            [RepositoryItem("117cc03f-c36f-450b-83c8-8af581d34d1a")]
            public virtual Ranorex.Text Text575
            {
                get
                {
                    return _text575Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text575 item info.
            /// </summary>
            [RepositoryItemInfo("117cc03f-c36f-450b-83c8-8af581d34d1a")]
            public virtual RepoItemInfo Text575Info
            {
                get
                {
                    return _text575Info;
                }
            }

            /// <summary>
            /// The Text882 item.
            /// </summary>
            [RepositoryItem("7d720947-c00d-44df-9bac-622cb3959bf8")]
            public virtual Ranorex.Text Text882
            {
                get
                {
                    return _text882Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text882 item info.
            /// </summary>
            [RepositoryItemInfo("7d720947-c00d-44df-9bac-622cb3959bf8")]
            public virtual RepoItemInfo Text882Info
            {
                get
                {
                    return _text882Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("02bb4fe4-2ad3-4fce-9f2a-b6e1191b87e8")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("02bb4fe4-2ad3-4fce-9f2a-b6e1191b87e8")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Quitter item.
            /// </summary>
            [RepositoryItem("6b86c337-78b5-4b48-aa87-b9d39966a5df")]
            public virtual Ranorex.Button Quitter
            {
                get
                {
                    return _quitterInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Quitter item info.
            /// </summary>
            [RepositoryItemInfo("6b86c337-78b5-4b48-aa87-b9d39966a5df")]
            public virtual RepoItemInfo QuitterInfo
            {
                get
                {
                    return _quitterInfo;
                }
            }

            /// <summary>
            /// The Text850 item.
            /// </summary>
            [RepositoryItem("053bf968-422d-4e5d-8004-2aa4c345c67f")]
            public virtual Ranorex.Text Text850
            {
                get
                {
                    return _text850Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text850 item info.
            /// </summary>
            [RepositoryItemInfo("053bf968-422d-4e5d-8004-2aa4c345c67f")]
            public virtual RepoItemInfo Text850Info
            {
                get
                {
                    return _text850Info;
                }
            }

            /// <summary>
            /// The Systeme item.
            /// </summary>
            [RepositoryItem("686c89c9-a7ed-4896-bcc8-c91f8414fceb")]
            public virtual Ranorex.MenuItem Systeme
            {
                get
                {
                    return _systemeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Systeme item info.
            /// </summary>
            [RepositoryItemInfo("686c89c9-a7ed-4896-bcc8-c91f8414fceb")]
            public virtual RepoItemInfo SystemeInfo
            {
                get
                {
                    return _systemeInfo;
                }
            }

            /// <summary>
            /// The Systeme1 item.
            /// </summary>
            [RepositoryItem("aa9b1792-9fde-4960-aa9f-de756481fc2d")]
            public virtual Ranorex.MenuBar Systeme1
            {
                get
                {
                    return _systeme1Info.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Systeme1 item info.
            /// </summary>
            [RepositoryItemInfo("aa9b1792-9fde-4960-aa9f-de756481fc2d")]
            public virtual RepoItemInfo Systeme1Info
            {
                get
                {
                    return _systeme1Info;
                }
            }

            /// <summary>
            /// The Fermer item.
            /// </summary>
            [RepositoryItem("04b022fe-ae5a-470f-b52b-f5c14ba98aec")]
            public virtual Ranorex.Button Fermer
            {
                get
                {
                    return _fermerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Fermer item info.
            /// </summary>
            [RepositoryItemInfo("04b022fe-ae5a-470f-b52b-f5c14ba98aec")]
            public virtual RepoItemInfo FermerInfo
            {
                get
                {
                    return _fermerInfo;
                }
            }

            /// <summary>
            /// The SectraMyrianOuvertureDeSession item.
            /// </summary>
            [RepositoryItem("4868a807-5af9-437c-b064-686b6ab1bbdc")]
            public virtual Ranorex.TitleBar SectraMyrianOuvertureDeSession
            {
                get
                {
                    return _sectramyrianouverturedesessionInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The SectraMyrianOuvertureDeSession item info.
            /// </summary>
            [RepositoryItemInfo("4868a807-5af9-437c-b064-686b6ab1bbdc")]
            public virtual RepoItemInfo SectraMyrianOuvertureDeSessionInfo
            {
                get
                {
                    return _sectramyrianouverturedesessionInfo;
                }
            }
        }

        /// <summary>
        /// The SectraMyrianAppFolder folder.
        /// </summary>
        [RepositoryFolder("03be1b1d-6e8b-4181-9336-f0579cfe4bfd")]
        public partial class SectraMyrianAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _afxwnd140Info;
            RepoItemInfo _button737Info;

            /// <summary>
            /// Creates a new SectraMyrian  folder.
            /// </summary>
            public SectraMyrianAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SectraMyrian", "/form[@title='Sectra Myrian ']", parentFolder, 30000, null, false, "03be1b1d-6e8b-4181-9336-f0579cfe4bfd", "")
            {
                _afxwnd140Info = new RepoItemInfo(this, "AfxWnd140", "element[@instance='0']", 30000, null, "53d4a2cd-373a-477e-b56e-aca294ac17cf");
                _button737Info = new RepoItemInfo(this, "Button737", "?/?/button[@controlid='737']", 30000, null, "c37a2ec2-6748-4dd3-bd2d-d000a3dc51f1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03be1b1d-6e8b-4181-9336-f0579cfe4bfd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03be1b1d-6e8b-4181-9336-f0579cfe4bfd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AfxWnd140 item.
            /// </summary>
            [RepositoryItem("53d4a2cd-373a-477e-b56e-aca294ac17cf")]
            public virtual Ranorex.Unknown AfxWnd140
            {
                get
                {
                    return _afxwnd140Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The AfxWnd140 item info.
            /// </summary>
            [RepositoryItemInfo("53d4a2cd-373a-477e-b56e-aca294ac17cf")]
            public virtual RepoItemInfo AfxWnd140Info
            {
                get
                {
                    return _afxwnd140Info;
                }
            }

            /// <summary>
            /// The Button737 item.
            /// </summary>
            [RepositoryItem("c37a2ec2-6748-4dd3-bd2d-d000a3dc51f1")]
            public virtual Ranorex.Button Button737
            {
                get
                {
                    return _button737Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button737 item info.
            /// </summary>
            [RepositoryItemInfo("c37a2ec2-6748-4dd3-bd2d-d000a3dc51f1")]
            public virtual RepoItemInfo Button737Info
            {
                get
                {
                    return _button737Info;
                }
            }
        }

        /// <summary>
        /// The ServeurDactivationIntrouvableAppFolder folder.
        /// </summary>
        [RepositoryFolder("b5798d18-0cd3-4264-95d3-cb4c85f444c2")]
        public partial class ServeurDactivationIntrouvableAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;

            /// <summary>
            /// Creates a new ServeurDactivationIntrouvable  folder.
            /// </summary>
            public ServeurDactivationIntrouvableAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ServeurDactivationIntrouvable", "/form[@title~'^Serveur\\ d''activation\\ intr']", parentFolder, 30000, null, false, "b5798d18-0cd3-4264-95d3-cb4c85f444c2", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlid='1']", 30000, null, "91d3f167-97f4-490e-9173-85e2be6b896b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b5798d18-0cd3-4264-95d3-cb4c85f444c2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b5798d18-0cd3-4264-95d3-cb4c85f444c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("91d3f167-97f4-490e-9173-85e2be6b896b")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("91d3f167-97f4-490e-9173-85e2be6b896b")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}