///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace launchMyrian
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validation recording.
    /// </summary>
    [TestModule("449a51de-8c47-418f-997c-2eb1391b165b", ModuleType.Recording, 1)]
    public partial class Validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the launchMyrianRepository repository.
        /// </summary>
        public static launchMyrianRepository repo = launchMyrianRepository.Instance;

        static Validation instance = new Validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Myrian'.", repo.Myrian.SelfInfo, new RecordItemIndex(0));
            Validate.Exists(repo.Myrian.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Myrian.Text882' at 60;16.", repo.Myrian.Text882Info, new RecordItemIndex(1));
            repo.Myrian.Text882.Click("60;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'myrian' with focus on 'Myrian.Text882'.", repo.Myrian.Text882Info, new RecordItemIndex(2));
            repo.Myrian.Text882.PressKeys("myrian");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Myrian.ButtonOK' at 37;9.", repo.Myrian.ButtonOKInfo, new RecordItemIndex(3));
            repo.Myrian.ButtonOK.Click("37;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SectraMyrian.AfxWnd140'.", repo.SectraMyrian.AfxWnd140Info, new RecordItemIndex(4));
            Validate.Exists(repo.SectraMyrian.AfxWnd140Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ServeurDactivationIntrouvable.Button1' at Center.", repo.ServeurDactivationIntrouvable.Button1Info, new RecordItemIndex(5));
            repo.ServeurDactivationIntrouvable.Button1.Click(1000);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SectraMyrian.Button737' at Center.", repo.SectraMyrian.Button737Info, new RecordItemIndex(6));
            repo.SectraMyrian.Button737.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Myrian'.", repo.Myrian.SelfInfo, new RecordItemIndex(7));
            Validate.Exists(repo.Myrian.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Myrian.Quitter' at Center.", repo.Myrian.QuitterInfo, new RecordItemIndex(8));
            repo.Myrian.Quitter.Click(1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
